# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/spes-misound/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter spes,$(TARGET_DEVICE)),)

endif
